### ISSUE TITLE
Support prefixed labels

### ISSUE THREAD

**Issue by adamralph** [Particular/GitHubReleaseNotes#26]
`Type: ...`, etc.

- [x] make changes - https://github.com/Particular/GitHubReleaseNotes/pull/27
- [x] release

**Comment by adamralph** [comment]
@andreasohlund @SzymonPobiega can you please check (and correct) the release checklist?

**Comment by andreasohlund** [comment]
Pbot needs to be modified yes. 

I wonder if we should disable the caretaker pings since no one looks at them anymore :(

**Comment by adamralph** [comment]
@andreasohlund do you have any idea how to deploy this for both the build server and pbot?

**Comment by andreasohlund** [comment]
redeploying the bot is described here https://github.com/Particular/PBot#how-do-i-build-and-deploy-a-change

Not sure about the buildserver cc @SzymonPobiega

**Comment by adamralph** [comment]
How do I deploy GitHubReleaseNotes for pbot to pick up?

**Comment by andreasohlund** [comment]
Hmm, I didn't know pbot had anything to do with the release notes?

**Comment by adamralph** [comment]
I was led to believe that pbot somehow uses GitHubReleaseNotes when issues are closed.

**Comment by adamralph** [comment]
After discussion with @andreasohlund it seems this repo may be defunct and all our release notes automation now lives in https://github.com/Particular/Automation.Engineering/tree/master/src/Engineering.ReleaseManagement

**Comment by johnsimons** [comment]
> it seems this repo may be defunct and all our release notes automation now lives in

:dizzy_face:

**Comment by adamralph** [comment]
@SzymonPobiega commented this morning that both GitHubReleaseNotes *and* AutomationEngineering are being used.

**Comment by johnsimons** [comment]
Extra redundancy!
On Wed, 9 Sep 2015 at 20:31 Adam Ralph <notifications@github.com> wrote:

> @SzymonPobiega <https://github.com/SzymonPobiega> commented this morning
> that both GitHubReleaseNotes *and* AutomationEngineering are being used.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/GitHubReleaseNotes/issues/26#issuecomment-138867729>
> .
>
-- 

*John Simons*
*Engineer, Particular Software*

Email*:*  john.simons@particular.net
Web:    www.particular.net

**Comment by adamralph** [comment]
@andreasohlund @Particular/engineers the change has hit master.

Does this indeed need to be released anywhere? Or is it just something people pick up manually when required?

**Comment by SzymonPobiega** [comment]
It should be deployed to the build server but it will affect only projects migrated to the latest deployment model (I hope most of them by now). Promote the `Build` to `Deploy` here http://builds.particular.net/project.html?projectId=Tooling_GitHubReleaseNotes&tab=projectOverview

**Comment by adamralph** [comment]
Done. Thanks!
